/*
 * Contact Emails
 *
 * Manages the emails used to contact a Contact.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gielisg@selectsoftware.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ContactEmailUsageUpdate : IEquatable<ContactEmailUsageUpdate>
    { 
        /// <summary>
        /// Gets or Sets ContactCode
        /// </summary>
        [DataMember(Name="ContactCode")]
        public ContactCode ContactCode { get; set; }

        /// <summary>
        /// Gets or Sets ContactEmailUsage
        /// </summary>
        [DataMember(Name="ContactEmailUsage")]
        public List<ContactEmailUsageUpdateItem> ContactEmailUsage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContactEmailUsageUpdate {\n");
            sb.Append("  ContactCode: ").Append(ContactCode).Append("\n");
            sb.Append("  ContactEmailUsage: ").Append(ContactEmailUsage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ContactEmailUsageUpdate)obj);
        }

        /// <summary>
        /// Returns true if ContactEmailUsageUpdate instances are equal
        /// </summary>
        /// <param name="other">Instance of ContactEmailUsageUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContactEmailUsageUpdate other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ContactCode == other.ContactCode ||
                    ContactCode != null &&
                    ContactCode.Equals(other.ContactCode)
                ) && 
                (
                    ContactEmailUsage == other.ContactEmailUsage ||
                    ContactEmailUsage != null &&
                    ContactEmailUsage.SequenceEqual(other.ContactEmailUsage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ContactCode != null)
                    hashCode = hashCode * 59 + ContactCode.GetHashCode();
                    if (ContactEmailUsage != null)
                    hashCode = hashCode * 59 + ContactEmailUsage.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ContactEmailUsageUpdate left, ContactEmailUsageUpdate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ContactEmailUsageUpdate left, ContactEmailUsageUpdate right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
